const fs=require('fs');
const dkd_file='src/screens/AdminCenterScreen.js';
let dkd_source=fs.readFileSync(dkd_file,'utf8');
const dkd_old="courierRow:{minHeight:64,flexDirection:'row',alignItems:'center',gap:9,borderBottomWidth:1,borderBottomColor:'rgba(255,255,255,.055)'},avatar:{width:40,height:40,borderRadius:14,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(94,235,255,.08)'},courierName:{color:dkd_palette.text,fontSize:13.5,fontWeight:'900'},courierMeta:{color:dkd_palette.soft,fontSize:10.5,fontWeight:'700',marginTop:2},courierMoney:{color:'#9FF0D2',fontSize:11.5,fontWeight:'900',textAlign:'right'},";
const dkd_next="courierCategoryHead:{minHeight:58,borderRadius:18,paddingHorizontal:12,marginTop:17,backgroundColor:'rgba(94,235,255,.06)',borderWidth:1,borderColor:'rgba(94,235,255,.12)',flexDirection:'row',alignItems:'center',gap:9},courierCategoryIcon:{width:38,height:38,borderRadius:13,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(94,235,255,.09)'},courierCategoryTitle:{flex:1,color:dkd_palette.text,fontSize:12,fontWeight:'900',letterSpacing:.7},courierCountBadge:{minWidth:30,height:27,borderRadius:10,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(94,235,255,.10)'},courierCountText:{color:dkd_palette.cyan,fontSize:11,fontWeight:'900'},courierCategoryBody:{paddingTop:3},courierSearchWrap:{minHeight:48,borderRadius:15,marginTop:8,paddingHorizontal:11,backgroundColor:'rgba(255,255,255,.035)',borderWidth:1,borderColor:'rgba(255,255,255,.07)',flexDirection:'row',alignItems:'center',gap:7},courierSearchInput:{flex:1,color:dkd_palette.text,fontSize:13.5,fontWeight:'800'},courierRow:{minHeight:64,flexDirection:'row',alignItems:'center',gap:9,borderBottomWidth:1,borderBottomColor:'rgba(255,255,255,.055)'},avatar:{width:40,height:40,borderRadius:14,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(94,235,255,.08)'},courierName:{color:dkd_palette.text,fontSize:13.5,fontWeight:'900'},courierMeta:{color:dkd_palette.soft,fontSize:10.5,fontWeight:'700',marginTop:2},courierMoneyWrap:{alignItems:'flex-end',maxWidth:112},courierMoney:{color:'#9FF0D2',fontSize:11.5,fontWeight:'900',textAlign:'right'},moreButton:{minHeight:48,borderRadius:15,marginTop:10,backgroundColor:dkd_palette.cyan,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},moreButtonText:{color:'#07111F',fontSize:11.5,fontWeight:'900'},";
if(dkd_source.includes(dkd_next)){console.log('Admin courier styles already applied.');process.exit(0);}
if(!dkd_source.includes(dkd_old))throw new Error('Exact admin courier style block not found');
dkd_source=dkd_source.replace(dkd_old,dkd_next);
fs.writeFileSync(dkd_file,dkd_source);
console.log('Admin courier styles applied.');
