const fs=require('fs');
const path=require('path');

function dkdReplaceRequired(file,oldText,newText,label){
  let source=fs.readFileSync(file,'utf8');
  if(source.includes(newText)) return;
  if(!source.includes(oldText)) throw new Error(`Missing ${label} in ${file}`);
  source=source.replace(oldText,newText);
  fs.writeFileSync(file,source);
}

function dkdWalk(dir){
  for(const name of fs.readdirSync(dir)){
    const file=path.join(dir,name);
    const stat=fs.statSync(file);
    if(stat.isDirectory()) dkdWalk(file);
    else if(file.endsWith('.js')){
      const source=fs.readFileSync(file,'utf8');
      const next=source.replace(/v0\.0\.2/gi,'v0.0.3');
      if(next!==source) fs.writeFileSync(file,next);
    }
  }
}

dkdWalk('src');

dkdReplaceRequired('App.js',"  { key:'settings',label:'Ayarlar',icon:'cog-outline',activeIcon:'cog' },\n",'', 'bottom settings tab');
dkdReplaceRequired('App.js',"{dkd_tab === 'dashboard' && <DashboardScreen business={dkd_business} refreshSignal={dkd_refresh_signal} />}","{dkd_tab === 'dashboard' && <DashboardScreen business={dkd_business} refreshSignal={dkd_refresh_signal} onOpenSettings={() => dkd_set_tab('settings')} />}",'dashboard settings route');

dkdReplaceRequired('src/screens/DashboardScreenPro.js','function DkdDashboardHero({ businessName, onRefresh, refreshing }) {','function DkdDashboardHero({ businessName, onRefresh, refreshing, onOpenSettings }) {','dashboard hero signature');
dkdReplaceRequired('src/screens/DashboardScreenPro.js','<Pressable onPress={onRefresh} disabled={refreshing} style={styles.refreshButton}><MaterialCommunityIcons name={refreshing ? \'progress-clock\' : \'refresh\'} size={22} color="#E8F7FF" /></Pressable>','<View style={styles.heroActions}><Pressable onPress={onOpenSettings} style={styles.settingsButton}><LinearGradient colors={[\'#66ECFF\',\'#8790FF\']} style={styles.settingsButtonGradient}><MaterialCommunityIcons name="tune-variant" size={22} color="#07131D" /></LinearGradient></Pressable><Pressable onPress={onRefresh} disabled={refreshing} style={styles.refreshButton}><MaterialCommunityIcons name={refreshing ? \'progress-clock\' : \'refresh\'} size={22} color="#E8F7FF" /></Pressable></View>','dashboard hero actions');
dkdReplaceRequired('src/screens/DashboardScreenPro.js','export default function DashboardScreenPro({ business, refreshSignal = 0 }) {','export default function DashboardScreenPro({ business, refreshSignal = 0, onOpenSettings }) {','dashboard component signature');
dkdReplaceRequired('src/screens/DashboardScreenPro.js','<DkdDashboardHero businessName={business?.dkd_business_name || dkd_data?.dkd_business_name} onRefresh={() => dkd_load(false)} refreshing={dkd_refreshing} />','<DkdDashboardHero businessName={business?.dkd_business_name || dkd_data?.dkd_business_name} onRefresh={() => dkd_load(false)} refreshing={dkd_refreshing} onOpenSettings={onOpenSettings} />','dashboard hero props');
dkdReplaceRequired('src/screens/DashboardScreenPro.js',"refreshButton: { width: 44, height: 44, borderRadius: 15, backgroundColor: 'rgba(255,255,255,.08)', alignItems: 'center', justifyContent: 'center' },","heroActions: { flexDirection: 'row', alignItems: 'center', gap: 7 }, settingsButton: { width: 46, height: 46, borderRadius: 16, overflow: 'hidden', borderWidth: 1, borderColor: 'rgba(115,235,255,.34)' }, settingsButtonGradient: { flex: 1, alignItems: 'center', justifyContent: 'center' }, refreshButton: { width: 44, height: 44, borderRadius: 15, backgroundColor: 'rgba(255,255,255,.08)', alignItems: 'center', justifyContent: 'center' },",'dashboard settings styles');

dkdReplaceRequired('src/components/CourierLiveDetailModal.js','function DkdMapSurface({','function DkdCourierMarker() {\n  return <View style={styles.courierMarker}><RacingMotorcycle color="#60ECFF" accentColor="#FFFFFF" size={44}/></View>;\n}\nfunction DkdMapSurface({','courier marker component');
dkdReplaceRequired('src/components/CourierLiveDetailModal.js','><DkdMarker icon="motorbike" /></MapboxGL.PointAnnotation>','><DkdCourierMarker /></MapboxGL.PointAnnotation>','courier map marker');
dkdReplaceRequired('src/components/CourierLiveDetailModal.js','<Text style={styles.title}>{courier.dkd_display_name || \'Kurye\'}</Text>','<Text style={styles.title} numberOfLines={1} ellipsizeMode="tail">{courier.dkd_display_name || \'Kurye\'}</Text>','single-line courier title');
dkdReplaceRequired('src/components/CourierLiveDetailModal.js',"marker:{width:42,height:42,borderRadius:999,backgroundColor:'#6DEBFF',borderWidth:3,borderColor:'#FFF',alignItems:'center',justifyContent:'center'},markerGreen:{backgroundColor:'#70EFB5',borderRadius:14},","courierMarker:{width:54,height:44,alignItems:'center',justifyContent:'center'},marker:{width:42,height:42,borderRadius:999,backgroundColor:'#6DEBFF',borderWidth:3,borderColor:'#FFF',alignItems:'center',justifyContent:'center'},markerGreen:{backgroundColor:'#70EFB5',borderRadius:14},",'courier marker style');

dkdReplaceRequired('src/screens/AdminCenterScreen.js',"import { ActivityIndicator, Animated, Easing, Linking, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';","import { ActivityIndicator, Alert, Animated, Easing, Linking, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';",'admin Alert import');
dkdReplaceRequired('src/screens/AdminCenterScreen.js',`  const dkd_save_fee = async()=>{\n    const dkd_business_id_value=dkd_business_detail?.dkd_business?.dkd_id; if(!dkd_business_id_value)return;\n    dkd_set_busy(true); try { await dkd_admin_set_platform_agreement(dkd_business_id_value,dkd_fee_mode,Number(String(dkd_fee_value).replace(',','.')) || 0); await dkd_open_business(dkd_business_id_value); await dkd_load_dashboard(); }\n    catch(dkd_error_value){ dkd_set_error(String(dkd_error_value.message || dkd_error_value)); dkd_set_busy(false); }\n  };`,`  const dkd_save_fee = async()=>{\n    const dkd_business_id_value=dkd_business_detail?.dkd_business?.dkd_id;\n    if(!dkd_business_id_value){ Alert.alert('İşletme seçilmedi','Önce anlaşma tanımlanacak işletmeyi aç.'); return; }\n    const dkd_numeric_value=Number(String(dkd_fee_value).replace(',','.'));\n    if(!Number.isFinite(dkd_numeric_value) || dkd_numeric_value<0){ Alert.alert('Geçersiz bedel','Platform Hizmet Bedeli için geçerli bir değer gir.'); return; }\n    dkd_set_busy(true); dkd_set_error('');\n    try {\n      await dkd_admin_set_platform_agreement(dkd_business_id_value,dkd_fee_mode,dkd_numeric_value);\n      const dkd_next_detail_value=await dkd_admin_fetch_business_detail(dkd_business_id_value);\n      dkd_set_business_detail(dkd_next_detail_value);\n      dkd_set_fee_mode(dkd_next_detail_value?.dkd_agreement?.dkd_fee_mode || dkd_fee_mode);\n      dkd_set_fee_value(String(dkd_next_detail_value?.dkd_agreement?.dkd_fee_value ?? dkd_numeric_value));\n      await dkd_load_dashboard();\n      Alert.alert('Anlaşma Kaydedildi',dkd_fee_mode==='percentage' ? 'Platform Hizmet Bedeli %'+dkd_numeric_value+' olarak aktif edildi.' : 'Platform Hizmet Bedeli '+dkd_numeric_value.toLocaleString('tr-TR')+' TL olarak aktif edildi.');\n    } catch(dkd_error_value){\n      const dkd_message_value=String(dkd_error_value.message || dkd_error_value);\n      dkd_set_error(dkd_message_value); Alert.alert('Kaydedilemedi',dkd_message_value);\n    } finally { dkd_set_busy(false); }\n  };`,'admin agreement save handler');
dkdReplaceRequired('src/screens/AdminCenterScreen.js',"dkd_admin_set_iban(dkd_iban,'DraBornGo')","dkd_admin_set_iban(dkd_iban,'Doğancan Kartal')",'admin recipient name');
dkdReplaceRequired('src/screens/AdminCenterScreen.js','<Pressable onPress={dkd_save_fee} style={styles.saveFeeButton}><LinearGradient colors={[\'#5EEBFF\',\'#6D8DFF\']} style={styles.saveFeeGradient}><MaterialCommunityIcons name="content-save-check" size={20} color="#07111F"/><Text style={styles.saveFeeText}>Kaydet</Text></LinearGradient></Pressable>','<Pressable onPress={dkd_save_fee} disabled={dkd_busy} style={styles.saveFeeButton}><LinearGradient colors={[\'#5EEBFF\',\'#6D8DFF\']} style={styles.saveFeeGradient}>{dkd_busy?<ActivityIndicator color="#07111F"/>:<><MaterialCommunityIcons name="content-save-check" size={20} color="#07111F"/><Text style={styles.saveFeeText}>Kaydet</Text></>}</LinearGradient></Pressable>','admin save busy feedback');

dkdReplaceRequired('src/screens/PlatformFeeScreen.js','<Text style={styles.bankBrand}>DraBornGo</Text>','<Text style={styles.bankBrand}>Doğancan Kartal</Text>','bank brand');
dkdReplaceRequired('src/screens/PlatformFeeScreen.js',"{dkd_data?.dkd_account_name || 'DraBornGo'}","{dkd_data?.dkd_account_name || 'Doğancan Kartal'}",'bank recipient fallback');
dkdReplaceRequired('src/screens/PlatformFeeScreen.js','<Text style={styles.bankLabel}>IBAN</Text><Text selectable style={[styles.bankValue,styles.ibanValue]}>{dkd_data?.dkd_iban || \'IBAN henüz Yönetim Merkezi tarafından tanımlanmadı.\'}</Text>','<View style={styles.ibanLabelRow}><Text style={styles.bankLabel}>IBAN</Text><View style={styles.copyHintWrap}><MaterialCommunityIcons name="content-copy" size={13} color={dkd_palette.cyan}/><Text style={styles.copyHint}>Basılı tut ve kopyala</Text></View></View><Text selectable selectionColor={dkd_palette.cyan} style={[styles.bankValue,styles.ibanValue]}>{dkd_data?.dkd_iban || \'IBAN henüz Yönetim Merkezi tarafından tanımlanmadı.\'}</Text>','copyable iban hint');
dkdReplaceRequired('src/screens/PlatformFeeScreen.js','<Pressable onPress={dkd_pick_receipt} style={[styles.receiptPicker,dkd_receipt&&styles.receiptPickerSelected]}><View style={[styles.receiptIcon,dkd_receipt&&styles.receiptIconSelected]}><MaterialCommunityIcons name={dkd_receipt?\'file-check\':\'file-upload-outline\'} size={24} color={dkd_receipt?dkd_palette.mint:dkd_palette.cyan}/></View><View style={{flex:1}}><Text style={styles.receiptName}>{dkd_receipt?.name || \'Dekont Seç\'}</Text><Text style={styles.receiptMeta}>{dkd_receipt?\'Dosya hazır • değiştirmek için dokun\':\'JPG, PNG, WEBP veya PDF • en fazla 10 MB\'}</Text></View><MaterialCommunityIcons name="chevron-right" size={22} color={dkd_palette.muted}/></Pressable>','<Animated.View style={[styles.receiptMotion,{transform:[{scale:dkd_pulse.interpolate({inputRange:[0,1],outputRange:[1,1.018]})}]}]}><Pressable onPress={dkd_pick_receipt}><LinearGradient colors={dkd_receipt?[\'rgba(99,237,194,.22)\',\'rgba(57,157,183,.12)\',\'rgba(166,107,255,.12)\']:[\'rgba(94,235,255,.20)\',\'rgba(91,120,255,.13)\',\'rgba(166,107,255,.13)\']} start={{x:0,y:0}} end={{x:1,y:1}} style={[styles.receiptPicker,dkd_receipt&&styles.receiptPickerSelected]}><Animated.View pointerEvents="none" style={[styles.receiptShine,{opacity:dkd_pulse.interpolate({inputRange:[0,1],outputRange:[.08,.32]})}]}/><View style={[styles.receiptIcon,dkd_receipt&&styles.receiptIconSelected]}><MaterialCommunityIcons name={dkd_receipt?\'file-check\':\'file-upload-outline\'} size={26} color={dkd_receipt?dkd_palette.mint:dkd_palette.cyan}/></View><View style={{flex:1}}><Text style={styles.receiptEyebrow}>{dkd_receipt?\'DEKONT HAZIR\':\'GÜVENLİ DOSYA YÜKLEME\'}</Text><Text style={styles.receiptName}>{dkd_receipt?.name || \'Dekont Seç\'}</Text><Text style={styles.receiptMeta}>{dkd_receipt?\'Dosya hazır • değiştirmek için dokun\':\'JPG, PNG, WEBP veya PDF • en fazla 10 MB\'}</Text></View><View style={styles.receiptArrow}><MaterialCommunityIcons name={dkd_receipt?\'check\':\'arrow-right\'} size={20} color={dkd_receipt?dkd_palette.mint:dkd_palette.cyan}/></View></LinearGradient></Pressable></Animated.View>','premium animated receipt picker');
dkdReplaceRequired('src/screens/PlatformFeeScreen.js',"bankLabel:{color:dkd_palette.muted,fontSize:10,fontWeight:'900',letterSpacing:.8,marginTop:8},bankValue:{color:dkd_palette.text,fontSize:15,fontWeight:'900',marginTop:4},ibanValue:{color:dkd_palette.cyan,lineHeight:21},","bankLabel:{color:dkd_palette.muted,fontSize:10,fontWeight:'900',letterSpacing:.8,marginTop:8},ibanLabelRow:{flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between',gap:8},copyHintWrap:{flexDirection:'row',alignItems:'center',gap:4,paddingHorizontal:8,paddingVertical:5,borderRadius:10,backgroundColor:'rgba(94,235,255,.07)'},copyHint:{color:dkd_palette.cyan,fontSize:9.5,fontWeight:'900'},bankValue:{color:dkd_palette.text,fontSize:15,fontWeight:'900',marginTop:4},ibanValue:{color:dkd_palette.cyan,lineHeight:21},",'iban styles');
dkdReplaceRequired('src/screens/PlatformFeeScreen.js',"receiptPicker:{minHeight:72,borderRadius:18,marginTop:11,padding:11,flexDirection:'row',alignItems:'center',gap:10,backgroundColor:'rgba(94,235,255,.05)',borderWidth:1,borderColor:'rgba(94,235,255,.13)'},receiptPickerSelected:{backgroundColor:'rgba(99,237,194,.05)',borderColor:'rgba(99,237,194,.15)'},receiptIcon:{width:45,height:45,borderRadius:15,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(94,235,255,.08)'},receiptIconSelected:{backgroundColor:'rgba(99,237,194,.08)'},receiptName:{color:dkd_palette.text,fontSize:13.5,fontWeight:'900'},receiptMeta:{color:dkd_palette.soft,fontSize:11,fontWeight:'700',marginTop:3},","receiptMotion:{marginTop:11,borderRadius:21},receiptPicker:{minHeight:84,borderRadius:21,padding:12,flexDirection:'row',alignItems:'center',gap:11,borderWidth:1,borderColor:'rgba(94,235,255,.24)',overflow:'hidden'},receiptPickerSelected:{borderColor:'rgba(99,237,194,.30)'},receiptShine:{position:'absolute',width:120,height:120,borderRadius:999,backgroundColor:'#FFFFFF',right:-55,top:-58},receiptIcon:{width:50,height:50,borderRadius:17,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(94,235,255,.10)',borderWidth:1,borderColor:'rgba(94,235,255,.16)'},receiptIconSelected:{backgroundColor:'rgba(99,237,194,.10)',borderColor:'rgba(99,237,194,.22)'},receiptEyebrow:{color:dkd_palette.cyan,fontSize:9,fontWeight:'900',letterSpacing:1},receiptName:{color:dkd_palette.text,fontSize:14.5,fontWeight:'900',marginTop:2},receiptMeta:{color:dkd_palette.soft,fontSize:11,fontWeight:'700',marginTop:3},receiptArrow:{width:38,height:38,borderRadius:13,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(5,10,24,.28)'},",'receipt premium styles');

console.log('DraBornGo Panel v0.0.3 requested fixes patched.');
