import React, { useEffect, useMemo, useRef } from 'react';
import { Animated, Easing, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { MaterialCommunityIcons } from '@expo/vector-icons';

const dkd_palette={bg:'#050816',text:'#F8FAFF',soft:'#96A5C5',muted:'#687895',cyan:'#5EEBFF',blue:'#718AFF',mint:'#63EDC2',purple:'#A66BFF',pink:'#FF76B7'};
const dkd_money=(dkd_value)=>`${Number(dkd_value || 0).toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2})} TL`;
const dkd_earning=(dkd_value)=>Number(dkd_value?.dkd_earnings_tl || 0);

function DkdMetric({label,value,icon,colors,delay=0}){
  const dkd_anim=useRef(new Animated.Value(0)).current;
  useEffect(()=>{Animated.timing(dkd_anim,{toValue:1,duration:520,delay,easing:Easing.out(Easing.cubic),useNativeDriver:true}).start();},[dkd_anim,delay]);
  return <Animated.View style={[styles.metricWrap,{opacity:dkd_anim,transform:[{translateY:dkd_anim.interpolate({inputRange:[0,1],outputRange:[16,0]})}]}]}><LinearGradient colors={colors} style={styles.metric}><View style={styles.metricIcon}><MaterialCommunityIcons name={icon} size={21} color="#07111F"/></View><Text style={styles.metricLabel}>{label}</Text><Text numberOfLines={1} adjustsFontSizeToFit style={styles.metricValue}>{value}</Text></LinearGradient></Animated.View>;
}

function DkdChart({rows,keyName,valueName,color}){
  const dkd_values=Array.isArray(rows)?rows:[];
  const dkd_max=Math.max(1,...dkd_values.map((dkd_row)=>Number(dkd_row?.[valueName] || 0)));
  if(!dkd_values.length)return <View style={styles.empty}><MaterialCommunityIcons name="chart-timeline-variant" size={26} color={dkd_palette.muted}/><Text style={styles.emptyText}>Henüz kazanç verisi yok.</Text></View>;
  return <View style={styles.chartList}>{dkd_values.map((dkd_row,dkd_index)=>{const dkd_value=Number(dkd_row?.[valueName] || 0);const dkd_width=Math.max(3,Math.min(100,(dkd_value/dkd_max)*100));return <View key={`${dkd_row?.[keyName] || dkd_index}-${dkd_index}`} style={styles.chartRow}><Text style={styles.chartLabel}>{String(dkd_row?.[keyName] ?? '')}</Text><View style={styles.chartTrack}><View style={[styles.chartFill,{width:`${dkd_width}%`,backgroundColor:color}]}/></View><Text style={styles.chartMoney}>{dkd_money(dkd_value)}</Text></View>;})}</View>;
}

export default function AdminCourierDetailScreen({detail,onBack}){
  const dkd_enter=useRef(new Animated.Value(0)).current;
  useEffect(()=>{Animated.timing(dkd_enter,{toValue:1,duration:560,easing:Easing.out(Easing.cubic),useNativeDriver:true}).start();},[dkd_enter]);
  const dkd_business=detail?.dkd_business || {};
  const dkd_daily=useMemo(()=>Array.isArray(detail?.dkd_daily_earnings)?detail.dkd_daily_earnings:[],[detail]);
  const dkd_hourly=useMemo(()=>Array.isArray(detail?.dkd_hourly_earnings)?detail.dkd_hourly_earnings:[],[detail]);
  return <View style={styles.root}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <Animated.View style={{opacity:dkd_enter,transform:[{translateY:dkd_enter.interpolate({inputRange:[0,1],outputRange:[18,0]})}]}}><LinearGradient colors={['#0C4560','#243C7D','#562F78']} start={{x:0,y:0}} end={{x:1,y:1}} style={styles.hero}><View style={styles.heroGlow}/><View style={styles.heroTop}><Pressable onPress={onBack} style={styles.backButton}><MaterialCommunityIcons name="arrow-left" size={23} color="#FFF"/></Pressable><View style={styles.heroBadge}><View style={styles.liveDot}/><Text style={styles.heroBadgeText}>KURYE DETAYI</Text></View></View><View style={styles.heroMain}><View style={styles.avatar}><MaterialCommunityIcons name="bike-fast" size={31} color="#07111F"/></View><View style={{flex:1,minWidth:0}}><Text numberOfLines={1} ellipsizeMode="tail" style={styles.heroTitle}>{detail?.dkd_display_name || 'Kurye'}</Text><Text numberOfLines={1} ellipsizeMode="tail" style={styles.heroSub}>{detail?.dkd_dbg_id || 'DBG ID yok'} • {dkd_business?.dkd_business_name || 'Bağlı işletme yok'}</Text></View></View></LinearGradient></Animated.View>

    <View style={styles.metricGrid}><DkdMetric label="BUGÜN" value={dkd_money(dkd_earning(detail?.dkd_today))} icon="calendar-today" colors={['#5EEBFF','#68A0FF']} delay={40}/><DkdMetric label="HAFTA" value={dkd_money(dkd_earning(detail?.dkd_week))} icon="calendar-week" colors={['#63EDC2','#46C8A5']} delay={90}/><DkdMetric label="AY" value={dkd_money(dkd_earning(detail?.dkd_month))} icon="calendar-month" colors={['#A66BFF','#FF76B7']} delay={140}/></View>

    <Text style={styles.eyebrow}>BAĞLI İŞLETME</Text><LinearGradient colors={['#0B1E33','#111B39']} style={styles.businessCard}><View style={styles.businessIcon}><MaterialCommunityIcons name="storefront-outline" size={23} color={dkd_palette.mint}/></View><View style={{flex:1,minWidth:0}}><Text numberOfLines={1} ellipsizeMode="tail" style={styles.businessName}>{dkd_business?.dkd_business_name || 'Bağlı işletme yok'}</Text><Text numberOfLines={1} ellipsizeMode="tail" style={styles.businessSub}>{dkd_business?.dkd_city || ''} {dkd_business?.dkd_district || ''}</Text></View><MaterialCommunityIcons name="shield-check" size={22} color={dkd_palette.mint}/></LinearGradient>

    <Text style={styles.eyebrow}>SON 31 GÜN</Text><Text style={styles.sectionTitle}>Gün Gün Kazanç</Text><View style={styles.panel}><DkdChart rows={dkd_daily} keyName="dkd_day" valueName="dkd_earnings_tl" color={dkd_palette.cyan}/></View>
    <Text style={styles.eyebrow}>BUGÜN</Text><Text style={styles.sectionTitle}>Saatlik Kazanç</Text><View style={styles.panel}><DkdChart rows={dkd_hourly} keyName="dkd_hour" valueName="dkd_earnings_tl" color={dkd_palette.blue}/></View>
    <View style={{height:28}}/>
  </ScrollView></View>;
}

const styles=StyleSheet.create({root:{flex:1,backgroundColor:dkd_palette.bg},content:{padding:16,paddingTop:18},hero:{borderRadius:30,padding:17,overflow:'hidden',borderWidth:1,borderColor:'rgba(255,255,255,.13)'},heroGlow:{position:'absolute',width:210,height:210,borderRadius:999,right:-90,top:-105,backgroundColor:'rgba(94,235,255,.14)'},heroTop:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},backButton:{width:46,height:46,borderRadius:16,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(5,10,24,.28)',borderWidth:1,borderColor:'rgba(255,255,255,.12)'},heroBadge:{flexDirection:'row',alignItems:'center',gap:7,paddingHorizontal:11,paddingVertical:8,borderRadius:999,backgroundColor:'rgba(5,10,24,.25)'},liveDot:{width:8,height:8,borderRadius:99,backgroundColor:dkd_palette.mint},heroBadgeText:{color:'#EAF9FF',fontSize:10.5,fontWeight:'900',letterSpacing:1},heroMain:{flexDirection:'row',alignItems:'center',gap:13,marginTop:18},avatar:{width:64,height:64,borderRadius:22,alignItems:'center',justifyContent:'center',backgroundColor:dkd_palette.cyan},heroTitle:{color:'#FFF',fontSize:28,fontWeight:'900'},heroSub:{color:'rgba(239,245,255,.76)',fontSize:13,fontWeight:'800',marginTop:5},metricGrid:{flexDirection:'row',gap:8,marginTop:14},metricWrap:{flex:1},metric:{minHeight:114,borderRadius:22,padding:11,justifyContent:'flex-end'},metricIcon:{position:'absolute',top:10,right:10,width:38,height:38,borderRadius:13,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(255,255,255,.42)'},metricLabel:{color:'rgba(5,12,25,.66)',fontSize:9.5,fontWeight:'900'},metricValue:{color:'#07111F',fontSize:15,fontWeight:'900',marginTop:4},eyebrow:{color:dkd_palette.cyan,fontSize:10.5,fontWeight:'900',letterSpacing:1.35,marginTop:22},sectionTitle:{color:dkd_palette.text,fontSize:22,fontWeight:'900',marginTop:4,marginBottom:10},businessCard:{minHeight:82,borderRadius:22,padding:12,flexDirection:'row',alignItems:'center',gap:11,borderWidth:1,borderColor:'rgba(99,237,194,.13)',marginTop:9},businessIcon:{width:48,height:48,borderRadius:16,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(99,237,194,.08)'},businessName:{color:dkd_palette.text,fontSize:16,fontWeight:'900'},businessSub:{color:dkd_palette.soft,fontSize:12,fontWeight:'700',marginTop:4},panel:{borderRadius:23,padding:13,backgroundColor:'#0C142B',borderWidth:1,borderColor:'rgba(112,144,207,.13)'},chartList:{gap:9},chartRow:{flexDirection:'row',alignItems:'center',gap:7},chartLabel:{width:72,color:dkd_palette.soft,fontSize:10,fontWeight:'800'},chartTrack:{flex:1,height:10,borderRadius:999,overflow:'hidden',backgroundColor:'rgba(255,255,255,.055)'},chartFill:{height:'100%',borderRadius:999},chartMoney:{width:84,color:dkd_palette.text,fontSize:10,fontWeight:'900',textAlign:'right'},empty:{alignItems:'center',padding:22},emptyText:{color:dkd_palette.soft,fontSize:12,fontWeight:'700',marginTop:7}});
