import React, { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Linking, Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import MapView, { Marker, Polyline } from 'react-native-maps';
import { LinearGradient } from 'expo-linear-gradient';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { dkd_panel_fetch_route, dkd_panel_geocode_address } from '../services/dkd_panel_mapbox_service';

function dkd_number(dkd_value){const dkd_n=Number(dkd_value);return Number.isFinite(dkd_n)?dkd_n:null;}
function dkd_point(dkd_lat,dkd_lng){const dkd_a=dkd_number(dkd_lat),dkd_b=dkd_number(dkd_lng);return dkd_a==null||dkd_b==null?null:{latitude:dkd_a,longitude:dkd_b};}

export default function CourierFullscreenRouteModal({ visible, courier, order, onClose }) {
  const [dkd_target,dkd_set_target]=useState(null); const [dkd_route,dkd_set_route]=useState({dkd_points_value:[],dkd_distance_km_value:null,dkd_duration_min_value:null}); const [dkd_loading,dkd_set_loading]=useState(false);
  const dkd_origin=useMemo(()=>dkd_point(order?.dkd_courier_lat??courier?.dkd_live_lat,order?.dkd_courier_lng??courier?.dkd_live_lng),[courier?.dkd_live_lat,courier?.dkd_live_lng,order?.dkd_courier_lat,order?.dkd_courier_lng]);
  useEffect(()=>{if(!visible)return;let dkd_cancelled=false;(async()=>{dkd_set_loading(true);try{let dkd_destination=dkd_point(order?.dkd_dropoff_lat,order?.dkd_dropoff_lng);if(!dkd_destination&&order?.dkd_dropoff)dkd_destination=await dkd_panel_geocode_address(order.dkd_dropoff);if(dkd_cancelled)return;dkd_set_target(dkd_destination);if(dkd_origin&&dkd_destination)dkd_set_route(await dkd_panel_fetch_route(dkd_origin,dkd_destination));else dkd_set_route({dkd_points_value:[],dkd_distance_km_value:null,dkd_duration_min_value:null});}finally{if(!dkd_cancelled)dkd_set_loading(false);}})();return()=>{dkd_cancelled=true;};},[visible,dkd_origin,order?.dkd_dropoff,order?.dkd_dropoff_lat,order?.dkd_dropoff_lng]);
  const dkd_region=useMemo(()=>{const dkd_list=[dkd_origin,dkd_target].filter(Boolean);if(!dkd_list.length)return{latitude:39.9334,longitude:32.8597,latitudeDelta:.12,longitudeDelta:.12};if(dkd_list.length===1)return{...dkd_list[0],latitudeDelta:.04,longitudeDelta:.04};const dkd_lat_delta=Math.max(Math.abs(dkd_list[0].latitude-dkd_list[1].latitude)*2.6,.03);const dkd_lng_delta=Math.max(Math.abs(dkd_list[0].longitude-dkd_list[1].longitude)*2.6,.03);return{latitude:(dkd_list[0].latitude+dkd_list[1].latitude)/2,longitude:(dkd_list[0].longitude+dkd_list[1].longitude)/2,latitudeDelta:dkd_lat_delta,longitudeDelta:dkd_lng_delta};},[dkd_origin,dkd_target]);
  const dkd_open_google=async()=>{const dkd_destination_text=dkd_target?`${dkd_target.latitude},${dkd_target.longitude}`:encodeURIComponent(String(order?.dkd_dropoff||''));const dkd_origin_text=dkd_origin?`&origin=${dkd_origin.latitude},${dkd_origin.longitude}`:'';const dkd_url=`https://www.google.com/maps/dir/?api=1&destination=${dkd_destination_text}${dkd_origin_text}&travelmode=driving`;await Linking.openURL(dkd_url);};
  return <Modal visible={Boolean(visible)} animationType="slide" onRequestClose={onClose}><View style={styles.root}><MapView style={StyleSheet.absoluteFill} region={dkd_region}>{dkd_route.dkd_points_value?.length>1?<Polyline coordinates={dkd_route.dkd_points_value} strokeWidth={6}/>:null}{dkd_origin?<Marker coordinate={dkd_origin} title={courier?.dkd_display_name||'Kurye'} description="Canlı kurye konumu"><View style={styles.markerCourier}><MaterialCommunityIcons name="motorbike" size={21} color="#07121D"/></View></Marker>:null}{dkd_target?<Marker coordinate={dkd_target} title="Teslimat" description={order?.dkd_dropoff||''}><View style={styles.markerTarget}><MaterialCommunityIcons name="map-marker-check" size={21} color="#07121D"/></View></Marker>:null}</MapView><LinearGradient colors={['rgba(5,13,25,.96)','rgba(10,25,46,.88)']} style={styles.topBar}><View style={styles.flexOne}><Text style={styles.kicker}>MAPBOX SÜRÜŞ ROTASI</Text><Text style={styles.title}>Aktif Kurye Haritası</Text><Text numberOfLines={1} style={styles.sub}>{order?.dkd_dropoff||'Teslimat adresi bekleniyor'}</Text></View><Pressable onPress={onClose} style={styles.iconButton}><MaterialCommunityIcons name="close" size={23} color="#FFF"/></Pressable></LinearGradient><LinearGradient colors={['rgba(7,19,34,.97)','rgba(18,20,47,.97)']} style={styles.bottomCard}>{dkd_loading?<ActivityIndicator color="#6DEBFF"/>:<><View style={styles.metric}><Text style={styles.metricLabel}>MESAFE</Text><Text style={styles.metricValue}>{dkd_route.dkd_distance_km_value!=null?`${dkd_route.dkd_distance_km_value.toFixed(1)} km`:'—'}</Text></View><View style={styles.metric}><Text style={styles.metricLabel}>VARIŞ</Text><Text style={styles.metricValue}>{dkd_route.dkd_duration_min_value!=null?`${dkd_route.dkd_duration_min_value} dk`:'—'}</Text></View></>}<Pressable onPress={dkd_open_google} style={styles.googleButton}><MaterialCommunityIcons name="google-maps" size={21} color="#07121D"/><Text style={styles.googleText}>GOOGLE MAPS ROTA</Text></Pressable></LinearGradient></View></Modal>;
}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:'#07111D'},topBar:{position:'absolute',left:12,right:12,top:14,borderRadius:22,padding:13,flexDirection:'row',alignItems:'center',gap:10,borderWidth:1,borderColor:'rgba(130,220,255,.18)'},flexOne:{flex:1,minWidth:0},kicker:{color:'#7EEBFF',fontSize:10.5,fontWeight:'900',letterSpacing:1},title:{color:'#FFF',fontSize:20,fontWeight:'900',marginTop:2},sub:{color:'#9CB1C8',fontSize:12.5,fontWeight:'700',marginTop:3},iconButton:{width:44,height:44,borderRadius:15,backgroundColor:'rgba(255,255,255,.08)',alignItems:'center',justifyContent:'center'},bottomCard:{position:'absolute',left:12,right:12,bottom:16,minHeight:92,borderRadius:22,padding:12,flexDirection:'row',alignItems:'center',gap:9,borderWidth:1,borderColor:'rgba(132,218,255,.16)'},metric:{minWidth:76},metricLabel:{color:'#7F96B1',fontSize:9.5,fontWeight:'900'},metricValue:{color:'#FFF',fontSize:14,fontWeight:'900',marginTop:4},googleButton:{marginLeft:'auto',minHeight:48,borderRadius:15,paddingHorizontal:13,backgroundColor:'#74E9FF',flexDirection:'row',alignItems:'center',gap:7},googleText:{color:'#07121D',fontSize:11.5,fontWeight:'900'},markerCourier:{width:40,height:40,borderRadius:14,backgroundColor:'#72EAFF',alignItems:'center',justifyContent:'center',borderWidth:3,borderColor:'#FFF'},markerTarget:{width:40,height:40,borderRadius:14,backgroundColor:'#76EFB8',alignItems:'center',justifyContent:'center',borderWidth:3,borderColor:'#FFF'}});
