import fs from 'node:fs';

function dkd_read(dkd_path){return fs.readFileSync(dkd_path,'utf8');}
function dkd_write(dkd_path,dkd_content){fs.writeFileSync(dkd_path,dkd_content);}
function dkd_replace(dkd_content,dkd_from,dkd_to,dkd_label){if(!dkd_content.includes(dkd_from)){if(dkd_content.includes(dkd_to))return dkd_content;throw new Error(`DKD patch pattern missing: ${dkd_label}`);}return dkd_content.replace(dkd_from,dkd_to);}

{
  const dkd_path='package.json'; const dkd_json=JSON.parse(dkd_read(dkd_path));
  dkd_json.dependencies={...(dkd_json.dependencies||{}),'expo-constants':'~57.0.0','expo-device':'~57.0.0','expo-notifications':'~57.0.0'};
  dkd_write(dkd_path,JSON.stringify(dkd_json,null,2)+'\n');
}
{
  const dkd_path='app.json'; const dkd_json=JSON.parse(dkd_read(dkd_path)); const dkd_plugins=Array.isArray(dkd_json.expo.plugins)?dkd_json.expo.plugins:[];
  if(!dkd_plugins.some((dkd_item)=>Array.isArray(dkd_item)?dkd_item[0]==='expo-notifications':dkd_item==='expo-notifications')) dkd_plugins.unshift(['expo-notifications',{defaultChannel:'draborngo-panel-orders',color:'#69EAFF'}]);
  dkd_json.expo.plugins=dkd_plugins;
  dkd_write(dkd_path,JSON.stringify(dkd_json,null,2)+'\n');
}
{
  const dkd_path='App.js'; let dkd_content=dkd_read(dkd_path);
  dkd_content=dkd_replace(dkd_content,"import { dkd_panel_ensure_business_profile, dkd_panel_fetch_business_profile, dkd_panel_subscribe_live } from './src/services/panelService';", "import { dkd_panel_ensure_business_profile, dkd_panel_fetch_business_profile, dkd_panel_subscribe_live } from './src/services/panelService';\nimport { dkd_panel_notify_new_order, dkd_panel_prime_notifications } from './src/services/dkd_panel_notification_service';",'App notification import');
  dkd_content=dkd_replace(dkd_content,"  useEffect(() => { dkd_load_profile(); }, [dkd_load_profile]);\n  useEffect(() => dkd_panel_subscribe_live(() => dkd_set_refresh_signal((dkd_value) => dkd_value + 1)), []);", "  useEffect(() => { dkd_load_profile(); }, [dkd_load_profile]);\n  useEffect(() => { dkd_panel_prime_notifications().catch(() => null); }, []);\n  useEffect(() => dkd_panel_subscribe_live((dkd_payload_value) => {\n    dkd_set_refresh_signal((dkd_value) => dkd_value + 1);\n    if (String(dkd_payload_value?.table || '') === 'dkd_courier_jobs' && String(dkd_payload_value?.eventType || '').toUpperCase() === 'INSERT') {\n      dkd_panel_notify_new_order(dkd_payload_value?.new || {}).catch(() => null);\n    }\n  }), []);",'App realtime notification effect');
  dkd_write(dkd_path,dkd_content);
}
{
  const dkd_path='src/screens/OrdersScreenV2.js'; let dkd_content=dkd_read(dkd_path);
  dkd_content=dkd_replace(dkd_content,"import { dkd_panel_create_order, dkd_panel_fetch_orders } from '../services/panelService';", "import { dkd_panel_create_order, dkd_panel_fetch_orders, dkd_panel_subscribe_live } from '../services/panelService';",'Orders realtime import');
  dkd_content=dkd_replace(dkd_content,"  const dkd_load = useCallback(async () => { dkd_set_refreshing(true); dkd_set_error(''); try { dkd_set_orders(await dkd_panel_fetch_orders(250)); } catch (dkd_error_value) { dkd_set_error(String(dkd_error_value.message || dkd_error_value)); } finally { dkd_set_loading(false); dkd_set_refreshing(false); } }, []);\n  useEffect(() => { dkd_load(); }, [dkd_load, refreshSignal]);", "  const dkd_load = useCallback(async (dkd_silent_value = false) => { if (!dkd_silent_value) dkd_set_refreshing(true); dkd_set_error(''); try { dkd_set_orders(await dkd_panel_fetch_orders(250)); } catch (dkd_error_value) { dkd_set_error(String(dkd_error_value.message || dkd_error_value)); } finally { dkd_set_loading(false); if (!dkd_silent_value) dkd_set_refreshing(false); } }, []);\n  useEffect(() => { dkd_load(false); }, [dkd_load, refreshSignal]);\n  useEffect(() => {\n    const dkd_unsubscribe_value = dkd_panel_subscribe_live((dkd_payload_value) => { if (String(dkd_payload_value?.table || '') === 'dkd_courier_jobs') dkd_load(true); });\n    const dkd_poll_value = setInterval(() => dkd_load(true), 5000);\n    return () => { clearInterval(dkd_poll_value); dkd_unsubscribe_value?.(); };\n  }, [dkd_load]);",'Orders auto refresh');
  dkd_write(dkd_path,dkd_content);
}
{
  const dkd_path='src/screens/ReportsScreen.js'; let dkd_content=dkd_read(dkd_path);
  dkd_content=dkd_replace(dkd_content,"import { dkd_panel_fetch_day_report } from '../services/panelService';", "import { dkd_panel_fetch_day_report } from '../services/panelService';\nimport ReportOrderDetailModal from '../components/ReportOrderDetailModal';",'Reports modal import');
  dkd_content=dkd_replace(dkd_content,"  const [dkd_day,dkd_set_day]=useState(dkd_date_string()); const [dkd_data,dkd_set_data]=useState({}); const [dkd_loading,dkd_set_loading]=useState(true); const [dkd_refreshing,dkd_set_refreshing]=useState(false); const [dkd_error,dkd_set_error]=useState('');", "  const [dkd_day,dkd_set_day]=useState(dkd_date_string()); const [dkd_data,dkd_set_data]=useState({}); const [dkd_loading,dkd_set_loading]=useState(true); const [dkd_refreshing,dkd_set_refreshing]=useState(false); const [dkd_error,dkd_set_error]=useState(''); const [dkd_selected_order,dkd_set_selected_order]=useState(null);",'Reports selected state');
  dkd_content=dkd_replace(dkd_content,"{dkd_orders.length?dkd_orders.map((dkd_order)=><View key={String(dkd_order.dkd_job_id)} style={styles.orderRow}><View style={styles.orderIcon}><MaterialCommunityIcons name=\"package-variant-closed-check\" size={20} color=\"#FFD779\"/></View><View style={{flex:1}}><Text style={styles.orderTitle}>#{dkd_order.dkd_order_ref} • {dkd_order.dkd_title}</Text><Text style={styles.orderSub}>{dkd_order.dkd_courier_name||'Kurye'} • {new Date(dkd_order.dkd_completed_at).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})}</Text></View><Text style={styles.orderAmount}>{dkd_money(dkd_order.dkd_amount_tl)}</Text></View>):", "{dkd_orders.length?dkd_orders.map((dkd_order)=><Pressable key={String(dkd_order.dkd_job_id)} onPress={()=>dkd_set_selected_order(dkd_order)} style={({pressed})=>[styles.orderRow,pressed&&{opacity:.72}]}><View style={styles.orderIcon}><MaterialCommunityIcons name=\"package-variant-closed-check\" size={20} color=\"#FFD779\"/></View><View style={{flex:1}}><Text style={styles.orderTitle}>#{dkd_order.dkd_order_ref} • {dkd_order.dkd_title}</Text><Text style={styles.orderSub}>{dkd_order.dkd_courier_name||'Kurye'} • {new Date(dkd_order.dkd_completed_at).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})}</Text></View><Text style={styles.orderAmount}>{dkd_money(dkd_order.dkd_amount_tl)}</Text><MaterialCommunityIcons name=\"chevron-right\" size={20} color=\"#78EAFF\"/></Pressable>):",'Reports clickable rows');
  dkd_content=dkd_replace(dkd_content,"<View style={{height:120}}/></ScrollView></View>;", "<View style={{height:120}}/></ScrollView><ReportOrderDetailModal visible={Boolean(dkd_selected_order)} order={dkd_selected_order} onClose={()=>dkd_set_selected_order(null)}/></View>;",'Reports modal render');
  dkd_write(dkd_path,dkd_content);
}
{
  const dkd_path='src/components/CourierLiveDetailModal.js'; let dkd_content=dkd_read(dkd_path);
  dkd_content=dkd_replace(dkd_content,"import React, { useMemo } from 'react';", "import React, { useMemo, useState } from 'react';",'Courier useState');
  dkd_content=dkd_replace(dkd_content,"import { dkd_theme } from '../lib/theme';", "import { dkd_theme } from '../lib/theme';\nimport CourierFullscreenRouteModal from './CourierFullscreenRouteModal';",'Courier fullscreen import');
  dkd_content=dkd_replace(dkd_content,"export default function CourierLiveDetailModal({ visible, courier, order, onClose }) {", "export default function CourierLiveDetailModal({ visible, courier, order, onClose }) {\n  const [dkd_fullscreen_map_value, dkd_set_fullscreen_map_value] = useState(false);",'Courier fullscreen state');
  dkd_content=dkd_replace(dkd_content,"            <View style={styles.mapLiveBadge}><View style={styles.liveDot} /><Text style={styles.mapLiveText}>CANLI TAKİP</Text></View>\n          </View>", "            <View style={styles.mapLiveBadge}><View style={styles.liveDot} /><Text style={styles.mapLiveText}>CANLI TAKİP</Text></View>\n            <Pressable onPress={() => dkd_set_fullscreen_map_value(true)} style={styles.mapExpandButton}><MaterialCommunityIcons name=\"arrow-expand-all\" size={21} color=\"#EAF9FF\" /></Pressable>\n          </View>\n          <Pressable onPress={() => dkd_set_fullscreen_map_value(true)} style={styles.routeButton}><MaterialCommunityIcons name=\"map-marker-path\" size={20} color=\"#07121D\"/><View style={{flex:1}}><Text style={styles.routeButtonTitle}>MAPBOX ROTA HARİTASINI AÇ</Text><Text style={styles.routeButtonSub}>Tam ekran rota • Google Maps alternatifi</Text></View><MaterialCommunityIcons name=\"chevron-right\" size={21} color=\"#07121D\"/></Pressable>",'Courier map controls');
  dkd_content=dkd_replace(dkd_content,"      </LinearGradient>\n    </View>\n  </Modal>;", "      </LinearGradient>\n    </View>\n    <CourierFullscreenRouteModal visible={dkd_fullscreen_map_value} courier={courier} order={order} onClose={() => dkd_set_fullscreen_map_value(false)} />\n  </Modal>;",'Courier fullscreen render');
  dkd_content=dkd_replace(dkd_content,"mapLiveText: { color: '#DDFBFF', fontSize: 11.5, fontWeight: '900' },", "mapLiveText: { color: '#DDFBFF', fontSize: 11.5, fontWeight: '900' }, mapExpandButton: { position: 'absolute', top: 12, right: 12, width: 42, height: 42, borderRadius: 14, backgroundColor: 'rgba(5,18,31,.90)', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(116,233,255,.22)' }, routeButton: { minHeight: 64, marginTop: 10, borderRadius: 18, backgroundColor: '#74E9FF', paddingHorizontal: 13, flexDirection: 'row', alignItems: 'center', gap: 9 }, routeButtonTitle: { color: '#07121D', fontSize: 12.5, fontWeight: '900' }, routeButtonSub: { color: '#254459', fontSize: 10.5, fontWeight: '800', marginTop: 2 },",'Courier map styles');
  dkd_write(dkd_path,dkd_content);
}
console.log('DKD Panel v0.0.2 realtime/notification patch applied.');
