-- DraBornGo / DraBornGo Panel shared courier live-operation hotfix.

create table if not exists public.dkd_native_push_tokens (
  dkd_id bigint generated by default as identity primary key,
  dkd_user_id uuid not null references auth.users(id) on delete cascade,
  dkd_token text not null unique,
  dkd_platform text,
  dkd_app_mode text,
  dkd_device_name text,
  dkd_is_active boolean not null default true,
  dkd_last_seen_at timestamptz not null default now(),
  dkd_created_at timestamptz not null default now(),
  dkd_updated_at timestamptz not null default now()
);
alter table public.dkd_native_push_tokens enable row level security;
revoke all on table public.dkd_native_push_tokens from anon, authenticated;
grant select, insert, update, delete on table public.dkd_native_push_tokens to service_role;
create index if not exists dkd_native_push_tokens_user_active_idx on public.dkd_native_push_tokens(dkd_user_id, dkd_is_active, dkd_last_seen_at desc);

create or replace function public.dkd_upsert_native_push_token(
  dkd_param_token text,
  dkd_param_platform text default null,
  dkd_param_app_mode text default null,
  dkd_param_device_name text default null
) returns jsonb language plpgsql security definer set search_path to 'public','auth' as $function$
declare dkd_user_id_value uuid:=auth.uid(); dkd_token_value text:=nullif(trim(coalesce(dkd_param_token,'')),'');
begin
  if dkd_user_id_value is null then return jsonb_build_object('dkd_ok_value',false,'dkd_reason_value','auth_required'); end if;
  if dkd_token_value is null then return jsonb_build_object('dkd_ok_value',false,'dkd_reason_value','token_required'); end if;
  insert into public.dkd_native_push_tokens(dkd_user_id,dkd_token,dkd_platform,dkd_app_mode,dkd_device_name,dkd_is_active,dkd_last_seen_at,dkd_created_at,dkd_updated_at)
  values(dkd_user_id_value,dkd_token_value,nullif(trim(coalesce(dkd_param_platform,'')),''),nullif(trim(coalesce(dkd_param_app_mode,'')),''),nullif(trim(coalesce(dkd_param_device_name,'')),''),true,now(),now(),now())
  on conflict(dkd_token) do update set dkd_user_id=excluded.dkd_user_id,dkd_platform=excluded.dkd_platform,dkd_app_mode=excluded.dkd_app_mode,dkd_device_name=excluded.dkd_device_name,dkd_is_active=true,dkd_last_seen_at=now(),dkd_updated_at=now();
  return jsonb_build_object('dkd_ok_value',true,'dkd_reason_value','native_push_token_upserted');
end;$function$;
grant execute on function public.dkd_upsert_native_push_token(text,text,text,text) to authenticated;

create table if not exists public.dkd_verified_delivery_places(
  dkd_id bigint generated by default as identity primary key,
  dkd_name text not null,
  dkd_aliases text[] not null default '{}'::text[],
  dkd_city text, dkd_district text, dkd_address_text text,
  dkd_lat numeric not null, dkd_lng numeric not null,
  dkd_is_active boolean not null default true,
  dkd_created_at timestamptz not null default now(), dkd_updated_at timestamptz not null default now()
);
alter table public.dkd_verified_delivery_places enable row level security;
revoke all on public.dkd_verified_delivery_places from anon, authenticated;
grant select on public.dkd_verified_delivery_places to service_role;
insert into public.dkd_verified_delivery_places(dkd_name,dkd_aliases,dkd_city,dkd_district,dkd_address_text,dkd_lat,dkd_lng,dkd_is_active)
select 'Göksu AVM',array['Göksu AVM Ankara','Goksu AVM Ankara','Göksu Alışveriş Merkezi','Goksu Alisveris Merkezi'],'Ankara','Etimesgut','Göksu Mah. Selçuklular Cad. No:57, Eryaman, Etimesgut, Ankara',39.986333,32.647732,true
where not exists(select 1 from public.dkd_verified_delivery_places where lower(dkd_name)=lower('Göksu AVM'));

create or replace function public.dkd_delivery_place_resolve_dkd(dkd_param_query text,dkd_param_city text default null)
returns jsonb language plpgsql stable security definer set search_path to 'public' as $function$
declare dkd_query_value text:=lower(trim(coalesce(dkd_param_query,''))); dkd_city_value text:=lower(trim(coalesce(dkd_param_city,''))); dkd_row_value public.dkd_verified_delivery_places%rowtype;
begin
  if dkd_query_value='' then return jsonb_build_object('dkd_ok_value',false,'dkd_reason_value','query_required'); end if;
  select p.* into dkd_row_value from public.dkd_verified_delivery_places p where p.dkd_is_active is true and (dkd_city_value='' or lower(coalesce(p.dkd_city,''))=dkd_city_value) and (dkd_query_value like '%'||lower(p.dkd_name)||'%' or exists(select 1 from unnest(p.dkd_aliases) dkd_alias_value where dkd_query_value like '%'||lower(dkd_alias_value)||'%' or lower(dkd_alias_value) like '%'||dkd_query_value||'%')) order by length(p.dkd_name) desc,p.dkd_id asc limit 1;
  if not found then return jsonb_build_object('dkd_ok_value',false,'dkd_reason_value','not_found'); end if;
  return jsonb_build_object('dkd_ok_value',true,'dkd_name',dkd_row_value.dkd_name,'dkd_address_text',dkd_row_value.dkd_address_text,'dkd_lat',dkd_row_value.dkd_lat,'dkd_lng',dkd_row_value.dkd_lng,'dkd_city',dkd_row_value.dkd_city,'dkd_district',dkd_row_value.dkd_district);
end;$function$;
grant execute on function public.dkd_delivery_place_resolve_dkd(text,text) to authenticated;

create or replace function public.dkd_courier_job_live_metrics_set_dkd(dkd_param_job_id bigint,dkd_param_distance_km numeric,dkd_param_eta_min integer)
returns jsonb language plpgsql security definer set search_path to 'public','auth' as $function$
declare dkd_user_id_value uuid:=auth.uid(); dkd_distance_value numeric:=greatest(0,coalesce(dkd_param_distance_km,0)); dkd_eta_value integer:=greatest(0,coalesce(dkd_param_eta_min,0));
begin
  if dkd_user_id_value is null then return jsonb_build_object('dkd_ok_value',false,'dkd_reason_value','auth_required'); end if;
  update public.dkd_courier_jobs set distance_km=round(dkd_distance_value,2),eta_min=dkd_eta_value,updated_at=now() where id=dkd_param_job_id and assigned_user_id=dkd_user_id_value and coalesce(is_active,true)=true;
  if not found then return jsonb_build_object('dkd_ok_value',false,'dkd_reason_value','job_not_assigned_or_inactive'); end if;
  return jsonb_build_object('dkd_ok_value',true,'dkd_distance_km',round(dkd_distance_value,2),'dkd_eta_min',dkd_eta_value);
end;$function$;
grant execute on function public.dkd_courier_job_live_metrics_set_dkd(bigint,numeric,integer) to authenticated;

create or replace function public.dkd_get_draborngo_firebase_service_account_json()
returns text language sql security definer set search_path to 'public','vault' as $function$
  select dkd_secret_value.decrypted_secret from vault.decrypted_secrets dkd_secret_value where dkd_secret_value.name='dkd_draborngo_firebase_service_account_json' limit 1;
$function$;
revoke all on function public.dkd_get_draborngo_firebase_service_account_json() from public,anon,authenticated;
grant execute on function public.dkd_get_draborngo_firebase_service_account_json() to service_role;

create or replace function public.dkd_courier_order_alert_webhook()
returns trigger language plpgsql security definer set search_path to 'public' as $function$
declare dkd_config_value public.dkd_internal_webhook_config%rowtype; dkd_event_value text:=''; dkd_old_status_value text:=''; dkd_new_status_value text:=lower(coalesce(new.status,'')); dkd_old_pickup_value text:=''; dkd_new_pickup_value text:=lower(coalesce(new.pickup_status,''));
begin
  select * into dkd_config_value from public.dkd_internal_webhook_config where dkd_key='courier_order_alert';
  if not found or coalesce(dkd_config_value.dkd_url,'')='' or coalesce(dkd_config_value.dkd_secret,'')='' then return new; end if;
  if tg_op='INSERT' then
    if coalesce(new.is_active,true)=true and dkd_new_status_value in('open','ready','published','pending','courier_pool','new','waiting') and new.assigned_user_id is null then dkd_event_value:='new_order'; else return new; end if;
  elsif tg_op='UPDATE' then
    dkd_old_status_value:=lower(coalesce(old.status,'')); dkd_old_pickup_value:=lower(coalesce(old.pickup_status,''));
    if (dkd_new_status_value in('completed','delivered','done','finished') or dkd_new_pickup_value in('delivered','completed')) and not(dkd_old_status_value in('completed','delivered','done','finished') or dkd_old_pickup_value in('delivered','completed')) then dkd_event_value:='delivered';
    elsif (dkd_new_status_value in('picked_up','to_customer','delivering') or dkd_new_pickup_value='picked_up') and not(dkd_old_status_value in('picked_up','to_customer','delivering') or dkd_old_pickup_value='picked_up') then dkd_event_value:='picked_up';
    elsif dkd_new_status_value in('accepted','assigned','to_pickup') and dkd_old_status_value not in('accepted','assigned','to_pickup') then dkd_event_value:='accepted'; else return new; end if;
  else return new; end if;
  perform net.http_post(url:=dkd_config_value.dkd_url,headers:=jsonb_build_object('Content-Type','application/json','x-dkd-webhook-secret',dkd_config_value.dkd_secret),body:=jsonb_build_object('type',tg_op,'table',tg_table_name,'schema',tg_table_schema,'event',dkd_event_value,'record',to_jsonb(new),'old_record',case when tg_op='UPDATE' then to_jsonb(old) else null end),timeout_milliseconds:=8000);
  return new;
exception when others then return new;
end;$function$;
